### ISSUE TITLE
Add support for automatic signing via xcodebuild

### ISSUE THREAD

**Issue by godrei** [bitrise-steplib/steps-xcode-archive#235]
# Feature Request description

https://discuss.bitrise.io/t/automatic-signing-via-xcodebuild/17133

Xcode 13 introduced new inputs for specifying Apple authentication properties (`-authenticationKeyPath`, `-authenticationKeyID` and `-authenticationKeyIssuerID`). 
This makes a CI environment able to utilize xcodebuild's auto code signing feature (can be enabled via the `-allowProvisioningUpdates` flag).

# Technical Plan

The new options can be used out-of-the-box, via the Step's `Additional options for xcodebuild call` (`xcodebuild_options`) Input.

```
    - xcode-archive:
        inputs:
        ...
        - xcodebuild_options: -allowProvisioningUpdates -authenticationKeyPath /path/to/AuthKey.p8 -authenticationKeyID KEY_ID -authenticationKeyIssuerID ISSUER_ID
```

There are multiple options for deeper integration:
- new specific Step Inputs for the authentication properties and for enabling xcodebuild's auto code signing
- integrating the Step with Bitrise Apple Service connection, so that no need for manually specifying the authentication properties, but the centralised API key connection can be used

The implementation should consider that Bitrise already has options for automatic code signing (via ios-auto-provision and ios-auto-provision-appstoreconnect steps).
